// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNoUeHj2ZQA21YuCRMOqpoUu-ylqGKBsQ',
    appId: '1:223753817709:web:51838f68d87a643d2cb964',
    messagingSenderId: '223753817709',
    projectId: 'rika-store-ccc49',
    authDomain: 'rika-store-ccc49.firebaseapp.com',
    storageBucket: 'rika-store-ccc49.firebasestorage.app',
    measurementId: 'G-FR5VNGH5DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcw9QUD_JVG42MALmFR88WQYWrlFqdKbo',
    appId: '1:223753817709:android:4afe10284502cf782cb964',
    messagingSenderId: '223753817709',
    projectId: 'rika-store-ccc49',
    storageBucket: 'rika-store-ccc49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT-U3L69mL356ba2nuEeoPoXal1x7TXqs',
    appId: '1:223753817709:ios:94fb05a16d773d642cb964',
    messagingSenderId: '223753817709',
    projectId: 'rika-store-ccc49',
    storageBucket: 'rika-store-ccc49.firebasestorage.app',
    iosBundleId: 'com.example.rikaOnlineStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT-U3L69mL356ba2nuEeoPoXal1x7TXqs',
    appId: '1:223753817709:ios:94fb05a16d773d642cb964',
    messagingSenderId: '223753817709',
    projectId: 'rika-store-ccc49',
    storageBucket: 'rika-store-ccc49.firebasestorage.app',
    iosBundleId: 'com.example.rikaOnlineStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNoUeHj2ZQA21YuCRMOqpoUu-ylqGKBsQ',
    appId: '1:223753817709:web:754bafb2fe8bdf5b2cb964',
    messagingSenderId: '223753817709',
    projectId: 'rika-store-ccc49',
    authDomain: 'rika-store-ccc49.firebaseapp.com',
    storageBucket: 'rika-store-ccc49.firebasestorage.app',
    measurementId: 'G-9NRKNXCW42',
  );
}
